### ISSUE TITLE
Impression résa : une URL apparaît à l'impression

### ISSUE THREAD

**Issue by josss000** [improcite/website-improcite#13]
Lorsqu'on imprime les résa, il y a des URL qui s'affichent autour des symboles : plus, moins, poubelle
réservation.php?id=...&action=

L'aperçu dans le navigateur est bon, c'est à l'impression que ça pêche.
Reproduit sur Edge et Chrome

**Comment by coudot** [comment]
Merci je vais regarder.

**Comment by coudot** [comment]
Correction possible indiquée ici : http://stackoverflow.com/questions/2162929/in-firefox-when-printing-a-page-with-anchor-tags-the-link-location-is-printing

Mais je vais continuer à chercher pour voir s'il n'y a pas un moyen plus propre de corriger ça.

**Comment by josss000** [comment]
P'tite remarque au passage : le site est pas du tout compatible avec php 7
(j'ai du tout réinstaller suite à mon changement de disque dur)

**Comment by coudot** [comment]
En effet mais le passage à php7 demande beaucoup d'adaptation du code

**Comment by coudot** [comment]
Le bug n'est pas encore corrigé

**Comment by coudot** [comment]
Fait dans commit f67bf793a011311a76aac7ccafe2a7606f825064
