### ISSUE TITLE
Evo : tâche CRON pour les dispos et rôles

### ISSUE THREAD

**Issue by josss000** [improcite/website-improcite#15]
Je le mets là pour y penser : à discuter / réfléchir. Déjà voir si notre hébergeur nous permet ça.

Dispos : tous les dimanches midi, un script fait un travail de vérif :
- Pour tous les comédiens
   - Pour tous les spectacles qui sont dans moins de x jours (x à définir)
   - Pour tous les entraînements qui sont dans moins de x jours (même x)
   - Envoi d'un mail pour mettre à jour les dispos

Rôles : lorsqu'un rôle est affecté, envoi d'un mail auto informant de la sélection (soit par CRON, soit directement à l'affectation)

**Comment by coudot** [comment]
On a déjà une tâche cron, mais il faut que je vérifie ce qu'elle fait exactement: https://github.com/improcite/website-improcite/tree/master/cron

**Comment by josss000** [comment]
Ah ouais, bien vu. Il y a p'tet pas le déclencheur alors ? pq elle l'a l'air de faire ça (pour les spectacles en tout cas, faudrait ajouter les trainings)

**Comment by coudot** [comment]
Je viens de faire plusieurs corrections, et programmer un envoi tous les dimanches à 18h. On verra demain si ça a marché.

**Comment by coudot** [comment]
ça semble avoir fonctionné.
